### ISSUE TITLE
Google Analytics requires integer timing

### ISSUE THREAD

**Issue by ejdaly** [ebidel/appmetrics.js#8]
My timing events were not showing up on GA. 

Forcing appmetrics to send integer values for time (ms) fixed this for me
https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#timingValue

A Math.round() in sendToAnalytics() will fix this in general:
`ga('send', 'timing', category, metric, Math.round(duration));`

**Comment by ebidel** [comment]
Huh. I haven't run into this myself but we should definitely follow the docs.
Interested in a PR?
